### ISSUE TITLE
[Meeting] [2024/04/11] Meeting Log

### ISSUE THREAD

**Issue by rlawjd10** [hi-sujung/hisujung-msa-k8s#6]
## 🔎 회의 안건
- [x] 메시징 아키텍처 설계 적합 여부
- [x] 간접 메시징 활용도

## 📚 내용 정리
**교수님 미팅**
- DB 분리 : `notice`에서 DB에 쿼리를 보내고, `notice recommend`는 `notice`의 API를 통해 접근해서 받도록 할 것
- `notice recommend` : 간접 통신 사용 적합
- MS마다 DB를 독립적으로 설계 및 MS 간 통신을 통해 데이터 주고받아야 하는 것이 중요
- 사용자 정보를 주고 받을 때, 토큰 없이 이메일 사용 여부
    -  교수님께서 추후에 일반적인 구현 방식 공지

## 💭 ToDo
- 교수님 조언 기반으로 MSA 아키텍처 수정

**Comment by suhyenim** [comment]
깔끔한 정리 좋습니다!
